### ISSUE TITLE
What's needed to let this work for any Swarm EC2

### ISSUE THREAD

**Issue by BretFisher** [mRoca/docker-swarm-aws-ecr-auth#1]
This looks like a nice simple solution to the ECR auth issue, but what would it take for this to work without the Docker for AWS CF Template? I see the other requirements listed in the README, but wondered what effort would be needed to expand the use case for any AWS Swarm.

Could it be as simple as providing `guide-aws` and `shell-aws` as services? I've not messed with then in D4AWS.

**Comment by mRoca** [comment]
We can easily use this image without the AWS official template, but it easier to use yet configured and running containers with the aws cli and the docker client sharing the host socket.

On another swarm stack (no created with the AWS template) the commands are simpler, as you can access the host (with the aws template, you're in a `shell-aws` container after a ssh connection) and use the https://github.com/awslabs/amazon-ecr-credential-helper credential helper, for exwample.

**Comment by BretFisher** [comment]
Thanks!
